### ISSUE TITLE
BCDevOps migration preparation

### ISSUE THREAD

**Issue by IanKWatts** [bcgov/developer-experience#5387]
**Describe the issue**
The GitHub repositories in the BCDevOps organization will be moved to either the bcgov or bcgov-c organizations, depending on if they are public (bcgov) or private (bcgov-c).  We should prepare for this migration.

The DevEx team wants to have the migration complete by the end of December.

When a GitHub repo is transferred to another org, redirects are automatically created on the GitHub side for both HTTP and SSH.

- When a user accesses the old repo URL in a browser, they are automatically redirected to the new correct URL.
- When a user uses the `git` CLI to update the repo, where the HTTPS URL is configured as the remote origin, they are still able to push using the old URL, but should update their local repo config for future reference. [1]
- As above, the `git` CLI will still work normally when using an SSH key for authentication.  The user will use the same method to update the remove URL. [1]

**What is the Value/Impact?**
Some of the repos in this org are regularly used by our team and we need to be ready.

**What is the plan? How will this get completed?**
Identify repos in this org that are used by the Platform Services team.
Update the ZenHub board with the new issue sources after the move.
Share information among the team to ensure a smooth transition.

**Identify any dependencies**
n/a

**Definition of done**
- [x] A list is prepared of the repos used by the Platform Services team
- [x] Work with the DevEx team to migrate the repos
- [x] For devops-requests and developer-experience, new sources have been added to the team's Zenhub board and the old sources removed

Repos:
- [x] developer-experience
- [x] devops-platform-workshops
- [x] platform-services
- [x] platform-services-status-page-notifications
- [x] devops-requests
- [x] openshift-tools
- [x] openshift-wiki

[1] To update the remote origin URL of your copy of a repo that has been migrated, see the following examples:
* HTTPS: `git remote set-url origin https://github.com/bcgov/migration-test.git`
* SSH: `git remote set-url origin git@github.com:bcgov/migration-test.git`

**Comment by IanKWatts** [comment]
List of BCDevOps repositories that are used or owned by the Platform Services team:
- developer-experience
- devops-platform-workshops
- platform-services
- platform-services-status-page-notifications
- devops-requests?
Seems like everything else is very old.

**Comment by ShellyXueHan** [comment]
I went through the repos, the only one I'm not sure about is https://github.com/BCDevOps/openshift-tools
